config/routes.rb
Sandbox::Application.routes.draw do
  resources :engagements do
    member do
      get "bonus"
    end
  end

  resources :jobs

end

app/models/engagement.rb
class Engagement < RubyDesk::Engagement
  include ActiveModel::Validations
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  
  @@team_ref = "344625"
  attributes :id
  
  def self.all(connector)
    return self.retrieve_all(connector, @@team_ref)
  end 
  
  def self.find(connector, eng_ref)
    return self.retrieve(connector, eng_ref)
  end 
  
  def self.initialize
    super
    id = reference
  end
  
  def self.initialize(attrs = {})
    super(attrs)
    id = reference
  end
  
  # Not stored in a DB, so not persistent (for ActiveModel)
  def persisted?
    false
  end

  # TODO: Issue with id... apparently, sometimes isn't created
  def to_s
    return reference
  end
  
  def pay_bonus(connector)
    amount = '0.05' # min payment is 0.05 (0.04 to contractor, 0.01 to odesk)
    comments = 'well done!'
    notes = 'Personal notes This is a test'
    options = {
                :engagement__reference => reference, :amount => amount,
                :comments => comments, :notes => notes
              }
    begin
      RubyDesk::CustomPayment.post(connector, @@team_ref, options)
    rescue
      # fail
    end
    redirect_to(engagements_path)
  end

end

app/models/job.rb
class Job < RubyDesk::HRJob
  include ActiveModel::Validations
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  
  @@team_ref = "344625"
  attributes :id
  
  def self.all(connector)
    return self.retrieve_all(connector, @@team_ref)
  end 
  
  def self.find(connector, job_ref)
    return self.retrieve(connector, job_ref)
  end 
  
  def self.initialize
    super
    id = reference
  end
  
  def self.initialize(attrs = {})
    super(attrs)
    id = reference
  end
  
  def get_offers(connector, jid)
    return Offer.retrieve_all(connector, @@team_ref, {:job__reference => jid})
  end
  
  def self.cancel!(connector, jid, reason)
    response = Job.cancel(connector, jid, reason)
    return response
  end
  
  def post(connector)
    options = {:job_data => {
                  :title => title,
                  :job_type => job_type,
                  :description => description,
                  :end_date => end_date,
                  :buyer_team__reference => buyer_team__reference,
                  :visibility => visibility,
                  :category => category,
                  :subcategory => subcategory
                  }
                  }
    
    if job_type == 'fixed-price'
      options[:job_data][:budget] = budget
    else
      options[:job_data][:duration] = duration
    end
    
    res = Job.post(connector, options)
  end
  
  # Not stored in a DB, so not persistent (for ActiveModel)
  def persisted?
    false
  end

  # TODO: Issue with id... apparently, sometimes isn't created
  def to_s
    return reference
  end

end

app/models/offer.rb
class Offer < RubyDesk::Offer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/engagements_controller.rb
class EngagementsController < ApplicationController
  before_filter :odesk_required
  
  def index
    @engagements = Engagement.all(@odesk_connector)
  end

  def show
    @engagement = Engagement.find(@odesk_connector, params[:id])
  end
  
  def bonus
    @engagement = Engagement.find(@odesk_connector, params[:id])
    @engagement.pay_bonus(@odesk_connector)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :odesk_required
  
  # GET /jobs
  def index
    @jobs = Job.all(@odesk_connector)
  end

  # GET /jobs/1
  def show
    @job = Job.find(@odesk_connector, params[:id])
    @offers = @job.get_offers(@odesk_connector, params[:id])
  end

  def new
    @team_options = []
    @roles = RubyDesk::UserRole.get_userroles(@odesk_connector)
    @roles.each do |role| # check perms later
      @team_options << [role.team__name, role.team__reference]
    end
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @team_options = []
    @roles = RubyDesk::UserRole.get_userroles(@odesk_connector)
    @roles.each do |role| # check perms later
      @team_options << [role.team__name, role.team__reference]
    end
    
    @job = Job.find(@odesk_connector, params[:id])
    # TODO: tmp fix, don't know how the integer rep of date from odesk works
    @job.start_date = nil
    @job.end_date = nil
  end

  # POST jobs
  def create
    fix_form_dates(params)
    
    @job = Job.new(params[:job])
    begin
        @job.post(@odesk_connector)
    rescue
        # bad request
    end
#    respond_to do |format|
      # if post successful, show success message
      # else, show errors
#    end
  end

  # PUT /jobs/1
  def update
    fix_form_dates(params)
#    @job = Job.find(@odesk_connector, params[:id])
    @job = Job.new(params[:job])
    begin
      @job.update(@odesk_connector)
    rescue
      # bad request
    end
      
    
#    respond_to do |format|
      # if update successful, say success
      # else, say errors
#    end
  end

  # DELETE jobs/1
  def destroy
    begin
      Job.cancel!(@odesk_connector, params[:id], ACCIDENTAL_OPENING_CREATION)
    rescue
      # forbidden; i.e. already cancelled or don't have permission to cancel
    end
    redirect_to(jobs_url)
  end
  
  # expects a params hash as we use in edit and create
  def fix_form_dates(params)
    year,month,day =  params[:job]["start_date(1i)"],
                      params[:job]["start_date(2i)"],
                      params[:job]["start_date(3i)"]
    date = month + '-' + day + '-' + year
    1.upto(3) {|x| params[:job].delete("start_date(#{x}i)")}
    params[:job].store(:start_date, date)
    
    y,m,d          =  params[:job]["end_date(1i)"],
                      params[:job]["end_date(2i)"],
                      params[:job]["end_date(3i)"]
    date_e = m + '-' + d + '-' + y
    1.upto(3) {|x| params[:job].delete("end_date(#{x}i)")}
    params[:job].store(:end_date, date_e)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engagement_helper.rb
module EngagementHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/views/engagements/bonus.html.erb
Paid bonus for <%= @engagement.reference %>

app/views/engagements/index.html.erb
<h1>Engagements</h1>

<table>
  <tr>
    <th>Reference</th>
    <th>Job reference</th>
    <th>Job title</th>
    <th>Provider Team</th>
    <th></th>
  </tr>

<% @engagements.each do |engagement| %>
  <tr>
    <td><%= engagement.reference %></td>
    <td><%= engagement.job__reference %></td>
    <td><%= engagement.job__title %></td>
    <td><%= engagement.provider_team__name %></td>
    <td><%= link_to 'Show', engagement.reference %></td>
  </tr>
<% end -%>
</table>

<br />

app/views/engagements/show.html.erb
<h1>Engagements#show</h1>

<p>
<b>Reference</b>:
<%= @engagement.reference %>
</p>

<p>
<b>Job reference</b>:
<%= @engagement.job__reference %>
</p>

<p>
<b>Job title</b>:
<%= @engagement.job__title %>
</p>

<p>
<b>Provider Team</b>:
<%= @engagement.provider_team__name %>
</p>


<%= 'pay bonus' %>

<br />

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :job_type %><br />
    <%= f.select :job_type, options_for_select(['fixed-price', 'hourly']) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    defaults to creation date
    <%= f.label :start_date %> (currently <%= @job.start_date %>)<br />
    <%= f.date_select :start_date, {:default => Date.today} %>
  </div>
  <div class="field">
    only for fixed price
    <%= f.label :end_date %>(currently <%= @job.end_date %>)<br />
    <%= f.date_select :end_date, {:default => 1.days.from_now} %>
  </div>
  <div class="field">
    <%= f.label :buyer_team__reference, "Buyer team" %><br />
    <%= f.select :buyer_team__reference, options_for_select(@team_options) %>
  </div>
  <div class="field">
    dropdown
    <%= f.label :visibility %><br />
    <%= f.select :visibility, options_for_select(['public', 'odesk', 'invite-only']) %>
  </div>
  <div class="field">
    add js for if job_type... fixed-price: budget; hourly: duration
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    dropdown
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    dropdown
    <%= f.label :subcategory %><br />
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    editing/updating only
    <%= f.label :status %><br />
    <%= f.select :status, options_for_select(['open', 'filled', 'cancelled']) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/cancel.html.erb
<h1>Job#cancel</h1>
<p>Find me in app/views/job/cancel.html.erb</p>

app/views/jobs/create.html.erb
<h1>Job#create</h1>
<p>Find me in app/views/job/create.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Job#edit</h1>
<%= render 'form' %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<table>
  <tr>
    <th>Reference</th>
    <th>Title</th>
    <th>Job type</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Buyer team reference</th>
    <th>Visibility</th>
    <th>Budget</th>
    <th>Duration</th>
    <th>Category</th>
    <th>Subcategory</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.reference %></td>
    <td><%= link_to job.title, job.public_url %></td>
    <td><%= job.job_type %></td>
    <td><%= job.description %></td>
    <td><%= job.start_date %></td>
    <td><%= job.end_date %></td>
    <td><%= job.buyer_team__reference %></td>
    <td><%= job.visibility %></td>
    <td><%= job.budget %></td>
    <td><%= job.duration %></td>
    <td><%= job.category %></td>
    <td><%= job.subcategory %></td>
    <td><%= job.status %> </td>
    <td><%= link_to 'Show', job.reference %></td>
    <td><%= (job.status != 'cancelled') ? link_to('Edit', edit_job_path(job.reference))  : '' %></td>
    <td><%= (job.status != 'cancelled') ? (link_to 'Cancel', job.reference, :confirm=>'Are you sure?', :method=>:delete) : '' %></td>
  </tr>
<% end -%>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>Job#new</h1>
<%= render 'form' %>

app/views/jobs/show.html.erb
<h1>Job#show</h1>

<p>
<b>Reference</b>:
<%= @job.reference %>
</p>

<p>
<b>Title</b>:
<%= link_to @job.title, @job.public_url %>
</p>

<p>
<b>Job type</b>:
<%= @job.job_type %>
</p>

<p>
<b>Description</b>:
<%= @job.description %>
</p>

<p>
<b>Start date</b>:
<%= @job.start_date %>
</p>

<p>
<b>End date</b>:
<%= @job.end_date %>
</p>

<p>
<b>Buyer team reference</b>:
<%= @job.buyer_team__reference %>
</p>

<p>
<b>Visibility</b>:
<%= @job.visibility %>
</p>

<p>
<b>Budget</b>:
<%= @job.budget %>
</p>

<p>
<b>Duration</b>:
<%= @job.duration %></td>
</p>

<p>
<b>Category</b>:
<%= @job.category %>
</p>

<p>
<b>Subcategory</b>:
<%= @job.subcategory %>
</p>

<p>
<b>Status</b>:
<%= @job.status %>
</p>


<%= (@job.status != 'cancelled') ? (link_to 'Edit', edit_job_path(@job.reference)) : '' %>
<%= (@job.status != 'cancelled') ? (link_to 'Cancel', @job.reference, :confirm=>'Are you sure?', :method=>:delete) : '' %>

<br />
<br />

<b>Offers</b>
<% @offers.each do |offer| %>
  hi
<% end -%>

<br />

app/views/jobs/update.html.erb
<h1>Job#update</h1>
<p>Find me in app/views/job/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>